DROP TABLE IF EXISTS users
CASCADE;

DROP TABLE IF EXISTS resources
CASCADE;

DROP TABLE IF EXISTS comments
CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  first_letter VARCHAR(1)
);

CREATE TABLE resources
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

  link VARCHAR(255) NOT NULL,
  bitly_link VARCHAR(255) NOT NULL,
  cover_photo_url VARCHAR(255),
  description TEXT,
  tag VARCHAR(32),
  date_created TIMESTAMP NOT NULL,

  total_upvotes INTEGER NOT NULL DEFAULT 0,
  total_downvotes INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE comments
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,

  comment TEXT,
  upvote BOOLEAN NOT NULL DEFAULT false,
  downvote BOOLEAN NOT NULL DEFAULT false,
  date_created TIMESTAMP NOT NULL
);


